### ISSUE TITLE
samba s6 package source verification

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [stevepacker/docker-containers#1]
The direct download of the s6-overlay is not verified.

Either the download should be verified against the public key:
https://github.com/just-containers/s6-overlay#verifying-downloads

Or their provided base image could be used:
https://github.com/just-containers/s6-overlay#our-s6-overlay-based-images

Or the stuff can be installed directly through the alpine package manager, like they do in their alpine base image:
https://github.com/harningt/docker-base-alpine-s6-overlay/blob/edge/Dockerfile

best,
Christian

**Comment by stevepacker** [comment]
Thanks for pointing this out and providing those links.  I decided against going the base-image route simply to minimize the number of layers, and instead now use `gpg` to do the verification.
