### ISSUE TITLE
Parse error: Duplicate status code entry: 508

### ISSUE THREAD

**Issue by psimonov** [stevepacker/docker-containers#2]
On startup:

`/etc/Caddyfile:42 - Parse error: Duplicate status code entry: 508`

Please, delete duplicate line in https://github.com/stevepacker/docker-containers/blob/caddy-php7/Caddyfile

**Comment by stevepacker** [comment]
Thanks @psimonov ... I usually volume-mount my own Caddyfile so I hadn't noticed this.
